from irover  import *
import time
i=IROVER()
i.OK()
i.sound(1000,1)
i.fill(0)
i.show()
i.servo(10,80)                                
i.motor(1,100)                                      
i.motor(2,-100) 	                                  
sleep(1)                                             
i.servo(15,0) 	                                  
sleep(1)                                             
i.servo(15,90)                                     
sleep(1)                                           
i.fd(100) 
sleep(1)                                             
i.bk(80) 	
sleep(1)                             
i.sl(60) 	 
sleep(1) 
i.sr(40) 	   
sleep(1) 
i.tl(60) 	 
sleep(1)                                       
i.fd2(100,50) 	                                    
sleep(1) 
i.bk2(55,50) 	                                       
sleep(1) 
i.stop()	 
while 1:
  valKnob=int(i.knob(0,255))
  i.fill(0)
  i.text("KNOB=%d " % i.knob(),0,0*8)
  i.text("IO34=%d " % i.analog(34),0,(1*8)+1)
  i.text("iKB_pin1=%d " % i.analog(i1,-100,100),0,(2*8)+1)
  i.text("iKB_pin0=%d " % i.input(i0),0,(3*8)+1)
  i.show()
  i.sled(1,(valKnob,valKnob,valKnob))
  i.output(i6,i.sw1())
    

